### ISSUE TITLE
crash on postgres replica

### ISSUE THREAD

**Issue by maxmeng-oss** [kestra-io/helm-charts#11]
### Expected Behavior

```
postgresql:
  enabled: true
  primary:    
    extendedConfiguration: |
        max_connections = 2048
    persistence:
      size: 1024Gi
  readReplicas:
    replicaCount: 2
    extendedConfiguration: |
        max_connections = 2048
    persistence:
      size: 1024Gi  
```

Should works well

### Actual Behaviour

Can't find kestra-postgres dns name.

After look into helm file https://github.com/kestra-io/helm-charts/blob/8a01e1b6f2521a760d034428d9166b9d8c127065/charts/kestra/templates/_helpers.tpl#L80-L82

I think no other helm that reads replic settings.

### Environment Information

- Kestra Version: 0.9.1
- Helm Charts version: 0.5.1
- Docker Image version: 0.9.1
