### ISSUE TITLE
No option for specifying basicAuth parameters in helm chart

### ISSUE THREAD

**Issue by imdmahajankanika** [kestra-io/helm-charts#116]
### Expected Behavior

Hello,

There is no way to specify below basicAuth parameters in HelmChart

```
kestra:
  url: https://kestra-url
  server:
    basic-auth:
      enabled: true
      username: ChangeMe
      password: 'changeMe'
```

### Environment Information

- Kestra Version:
- Helm Charts version:
- Docker Image version:
