### ISSUE TITLE
DIND not working in standard GKE

### ISSUE THREAD

**Issue by alucryd** [kestra-io/helm-charts#26]
### Expected Behavior

Trying to install the chart in a standard GKE cluster (Autopilot is out because of DIND, and potentially ES which requires a privileged pod) with basically all default values should run out of the box.

### Actual Behaviour

However the worker pod is stuck in a boot loop.

![Screenshot from 2024-01-09 16-54-20](https://github.com/kestra-io/helm-charts/assets/1561084/a38be9db-ce65-4bcf-bdef-756b9d9210ce)

I deactivated DIND for now so that I can test Kestra, but I can reactivate it to provide logs in a better format if needed.

### Steps To Reproduce

- Create a standard GKE cluster with default configuration
- Install the kestra helm chart with the values below

### Environment Information

- Kestra Version: 0.13.8
- Helm Charts version: 0.13.0
- Docker Image version: latest-full

`values.yaml`
```
deployments:
  webserver:
    enabled: true
  executor:
    enabled: true
  indexer:
    enabled: false
  scheduler:
    enabled: true
  worker:
    enabled: true
  standalone:
    enabled: false
```
