### ISSUE TITLE
ingress:  Required value: pathType must be specified

### ISSUE THREAD

**Issue by AllenX2018** [kestra-io/helm-charts#3]
### Expected Behavior

with kube `v1.23.5` which require  pathType
```
        {{- range .paths }}
          - path: {{ . }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
        {{- end }}
```

### Actual Behaviour

Failed to upgrade

### Environment Information

- Kestra Version: master
- Helm Charts version: 3.8.1
- Docker Image version: 1.23.5
