### ISSUE TITLE
Allow setting a custom chart version of the postgres dependency

### ISSUE THREAD

**Issue by aresfkonrad** [kestra-io/helm-charts#51]
### Feature description

The version 15 of the postgresql helm chart introduced the automatic retrieval of security parameters for Openshift. This would be very helpful for users who deploy kestra on openshift.

Currently the postgresql helm chart version, that Kestra uses is set to v12.2.2. This version lacks the features introduced in the later 3 versions.

Additionally, the values that are set for the postgres subchart did not experience any changes. So no adaptions in the values.yaml template are needed.

**Comment by anna-geller** [comment]
quickly checking, it seems we can make that configurable:

values.yaml:
```yaml
postgresql:
  enabled: true
  chartVersion: "12.2.2"  # Default value, can be overridden
```

Chart.yaml:

```yaml
dependencies:
  - name: postgresql
    version: {{ .Values.postgresql.chartVersion }}
    repository: https://charts.bitnami.com/bitnami
```

then:
```
helm install my-release --set postgresql.chartVersion=15.0.0
```
