### ISSUE TITLE
External MysqlDB support for Kestra in EKS 

### ISSUE THREAD

**Issue by surya9teja** [kestra-io/helm-charts#53]
### Issue description

As the title implies, Is it possible to use MysqlDb as the backend database for Kestra. If yes, How can I configure the values.yaml file in helm chart to point out to my external db?

**Comment by paulgrainger85** [comment]
Hi, yes you need to make 2 changes to the default helm values:
1. Disable the PG pod https://github.com/kestra-io/helm-charts/blob/a0fee7fab41fd0c37b4116afa91bfff6d23999fa/charts/kestra/values.yaml#L190
3. Add the following configuration to the values
```
configuration:
  datasources:
    mysql:
      url: jdbc:mysql://mysql-host:mysql-port/db_name
      driverClassName: com.mysql.cj.jdbc.Driver 
      dialect: MYSQL
      username: mysql_user
      password: mysql_pass
```

If you wish to source the above from a secret, you can see some examples in the values.yaml file
https://github.com/kestra-io/helm-charts/blob/a0fee7fab41fd0c37b4116afa91bfff6d23999fa/charts/kestra/values.yaml#L43
