### ISSUE TITLE
Can I use an external MinIO cluster and external postgresql server

### ISSUE THREAD

**Issue by AHulshoff** [kestra-io/helm-charts#65]
### Issue description

Currently, I am trying to configure Kestra in my own kubernetes cluster. However, I don't want to use the provided MinIO and Postgresql charts. I prefer to use the existing MinIO cluster and Postgresql server in my network. How can I accomplish that? 

I am trying to install Kestra with the official helm chart v0.19.
My values.yaml looks like as follows at the moment:

```yaml
deployments:
  webserver:
    enabled: true
  executor:
    enabled: true
  indexer:
    enabled: true
  scheduler:
    enabled: true
  worker:
    enabled: true
  standalone:
    enabled: false
configuration:
  datasources:
    postgres:
      url: jdbc:postgresql://<pgsql_svc>:5432/kestra
      username: <redacted>
      password: <redacted>
storage:
  type: minio
  minio:
    endpoint: http://<minio_svc>
    port: 9000
    access-key: <redacted>
    secret-key: <redacted>
    secure: false
    bucket: kestra
minio:
  enabled: false
postgresql:
  enabled: false
```
